# Set the default logging level
.level = INFO

# Suppress duplicate scanning warnings by raising the level to SEVERE
org.eclipse.tags.shaded.org.apache.xpath.operations.level = SEVERE
org.eclipse.tags.shaded.org.apache.xalan.xsltc.dom.level = SEVERE
org.eclipse.tags.shaded.org.apache.xalan.templates.level = SEVERE
org.apache.taglibs.standard.lang.jstl.level = SEVERE