# Specify the handlers to create
handlers = java.util.logging.ConsoleHandler

# Set the default logging level for the root logger
.level = INFO

# Set the default logging level for new ConsoleHandler instances
java.util.logging.ConsoleHandler.level = INFO

# Suppress specific package warnings
org.eclipse.tags.shaded.level = SEVERE
org.eclipse.jetty.annotations.level=SEVERE
org.eclipse.jetty.annotations.AnnotationParser.level = SEVERE

