/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.9
 * Generated at: 2025-04-25 19:16:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import com.ABETAppTeam.FCAR;
import com.ABETAppTeam.Course;
import com.ABETAppTeam.User;
import com.ABETAppTeam.Professor;
import java.util.HashMap;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ABETAppTeam.Course");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ABETAppTeam.User");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ABETAppTeam.Professor");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("com.ABETAppTeam.FCAR");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Admin Dashboard</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"dashboard\" id=\"adminDashboard\">\r\n");
      out.write("    <div class=\"header-container\">\r\n");
      out.write("        <h1>Admin Dashboard</h1>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"btn\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Status Key -->\r\n");
      out.write("    <div class=\"status-key\">\r\n");
      out.write("        <div><span class=\"status draft\"></span> Draft</div>\r\n");
      out.write("        <div><span class=\"status submitted\"></span> Submitted</div>\r\n");
      out.write("        <div><span class=\"status approved\"></span> Approved</div>\r\n");
      out.write("        <div><span class=\"status rejected\"></span> Rejected</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Statistics Section -->\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Dashboard Statistics</h2>\r\n");
      out.write("        <div class=\"stat-container\">\r\n");
      out.write("            ");

                List<FCAR> allFCARs = (List<FCAR>) request.getAttribute("allFCARs");
                Map<String, Integer> fcarStatusCounts = (Map<String, Integer>) request.getAttribute("fcarStatusCounts");
                if (fcarStatusCounts == null) {
                    fcarStatusCounts = new HashMap<>();
                }

                int totalFCARs = allFCARs != null ? allFCARs.size() : 0;
                int draftCount = fcarStatusCounts.getOrDefault("Draft", 0);
                int submittedCount = fcarStatusCounts.getOrDefault("Submitted", 0);
                int approvedCount = fcarStatusCounts.getOrDefault("Approved", 0);
                int rejectedCount = fcarStatusCounts.getOrDefault("Rejected", 0);
            
      out.write("\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Total FCARs</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( totalFCARs );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Draft</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( draftCount );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Submitted</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( submittedCount );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Approved</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( approvedCount );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Rejected</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( rejectedCount );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Action Buttons -->\r\n");
      out.write("    <div class=\"action-buttons\">\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ViewFCARServlet\" method=\"get\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"viewAll\"/>\r\n");
      out.write("            <button type=\"submit\" class=\"btn\">View All FCARs</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- View FCARs Section -->\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Manage FCARs</h2>\r\n");
      out.write("\r\n");
      out.write("        <!-- Dynamically display all FCARs -->\r\n");
      out.write("        <div id=\"fcarList\">\r\n");
      out.write("            <h3>Existing FCARs</h3>\r\n");
      out.write("            ");

                if (allFCARs != null && !allFCARs.isEmpty()) {
            
      out.write("\r\n");
      out.write("            <div class=\"fcar-box\">\r\n");
      out.write("                ");

                    for (FCAR fcar : allFCARs) {
                        String status = fcar.getStatus().toLowerCase();
                
      out.write("\r\n");
      out.write("                <div class=\"fcar-item\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <span class=\"status ");
      out.print( status );
      out.write("\"></span>\r\n");
      out.write("                        <strong>Course:</strong> ");
      out.print( fcar.getCourseId() );
      out.write(" -\r\n");
      out.write("                        <strong>Professor:</strong> ");
      out.print( fcar.getProfessorId() );
      out.write(" -\r\n");
      out.write("                        <strong>Semester:</strong> ");
      out.print( fcar.getSemester() );
      out.write(' ');
      out.print( fcar.getYear() );
      out.write(" -\r\n");
      out.write("                        <strong>Status:</strong> ");
      out.print( fcar.getStatus() );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fcar-actions\">\r\n");
      out.write("                        <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ViewFCARServlet\" style=\"display:inline;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"fcarId\" value=\"");
      out.print( fcar.getFcarId() );
      out.write("\"/>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\">View</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" style=\"display:inline;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"editFCAR\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"fcarId\" value=\"");
      out.print( fcar.getFcarId() );
      out.write("\"/>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\">Edit</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        ");
 if ("submitted".equals(status)) { 
      out.write("\r\n");
      out.write("                        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" style=\"display:inline;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"approveFCAR\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"fcarId\" value=\"");
      out.print( fcar.getFcarId() );
      out.write("\"/>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\" style=\"background-color: #28a745;\">Approve</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" style=\"display:inline;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"rejectFCAR\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"fcarId\" value=\"");
      out.print( fcar.getFcarId() );
      out.write("\"/>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\" style=\"background-color: #dc3545;\">Reject</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <p>No FCARs available.</p>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 'Create New FCAR' section -->\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Create New FCAR</h2>\r\n");
      out.write("        <div class=\"form-section\">\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" method=\"post\" id=\"createFcarForm\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"createFCAR\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"selectedOutcomes\" id=\"selectedOutcomesInput\" value=\"\" />\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"courseId\">Course:</label>\r\n");
      out.write("                    <select id=\"courseId\" name=\"courseId\" required>\r\n");
      out.write("                        <option value=\"\">Select a Course</option>\r\n");
      out.write("                        ");

                            List<Course> courses = (List<Course>) request.getAttribute("courses");
                            if (courses != null && !courses.isEmpty()) {
                                for (Course course : courses) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( course.getCourseId() );
      out.write('"');
      out.write('>');
      out.print( course.getCourseCode() );
      out.write(':');
      out.write(' ');
      out.print( course.getCourseName() );
      out.write("</option>\r\n");
      out.write("                        ");

                            }
                        } else {
                        
      out.write("\r\n");
      out.write("                        <option value=\"CS101\">CS101 - Fundamentals of Computer Science I</option>\r\n");
      out.write("                        <option value=\"CS201\">CS201 - Fundamentals of Computer Science II</option>\r\n");
      out.write("                        <option value=\"CS320\">CS320 - Software Engineering Design</option>\r\n");
      out.write("                        <option value=\"CS330\">CS330 - Network/App Protocols</option>\r\n");
      out.write("                        <option value=\"CS335\">CS335 - Cybersecurity Analysis & Application</option>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"professorId\">Assign to Professor:</label>\r\n");
      out.write("                    <select id=\"professorId\" name=\"professorId\" required>\r\n");
      out.write("                        <option value=\"\">Select a Professor</option>\r\n");
      out.write("                        ");

                            List<User> users = (List<User>) request.getAttribute("users");
                            if (users != null && !users.isEmpty()) {
                                for (User user : users) {
                                    if (user instanceof Professor) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( user.getUserId() );
      out.write('"');
      out.write('>');
      out.print( user.getFirstName() );
      out.write(' ');
      out.print( user.getLastName() );
      out.write("</option>\r\n");
      out.write("                        ");

                                }
                            }
                        } else {
                        
      out.write("\r\n");
      out.write("                        <option value=\"Smith\">Dr. Smith</option>\r\n");
      out.write("                        <option value=\"Johnson\">Dr. Johnson</option>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"semester\">Semester:</label>\r\n");
      out.write("                    <select id=\"semester\" name=\"semester\" required>\r\n");
      out.write("                        <option value=\"Spring\">Spring</option>\r\n");
      out.write("                        <option value=\"Summer\">Summer</option>\r\n");
      out.write("                        <option value=\"Fall\">Fall</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"year\">Year:</label>\r\n");
      out.write("                    <input type=\"number\" id=\"year\" name=\"year\" min=\"2020\" max=\"2030\" value=\"2025\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Outcomes and Indicators Section -->\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Student Learning Outcomes and Indicators:</label>\r\n");
      out.write("                    <div id=\"outcomesContainer\" class=\"outcomes-container\">\r\n");
      out.write("                        <div id=\"courseOutcomesPlaceholder\">\r\n");
      out.write("                            <p>Please select a course to see the associated outcomes and indicators.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Dynamic Course Outcomes Container -->\r\n");
      out.write("                        <div id=\"dynamicCourseOutcomes\" style=\"display: none;\">\r\n");
      out.write("                            <!-- This will be populated dynamically by JavaScript -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"targetGoal\">Target Goal (%):</label>\r\n");
      out.write("                    <input type=\"number\" id=\"targetGoal\" name=\"targetGoal\" min=\"0\" max=\"100\" value=\"70\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn-submit\">Create FCAR</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    ");
 
    // Check if outcomeData is available from the controller
    String outcomeData = (String) request.getAttribute("outcomeData");
    if (outcomeData != null && !outcomeData.isEmpty()) {
        // Output the data from the controller
        out.println(outcomeData);
    } else {
        // Fallback to hardcoded data if controller data is not available
    
      out.write("\r\n");
      out.write("    // Outcome descriptions\r\n");
      out.write("    const outcomeDescriptions = {\r\n");
      out.write("        1: \"Analyze a complex computing problem and to apply principles of computing and other relevant disciplines to identify solutions.\",\r\n");
      out.write("        2: \"Design, implement, and evaluate a computing-based solution to meet a given set of computing requirements in the context of the program's discipline.\",\r\n");
      out.write("        3: \"Communicate effectively in a variety of professional contexts.\",\r\n");
      out.write("        4: \"Recognize professional responsibilities and make informed judgments in computing practice based on legal and ethical principles.\",\r\n");
      out.write("        5: \"Function effectively as a member or leader of a team engaged in activities appropriate to the program's discipline.\",\r\n");
      out.write("        6: \"Apply computer science theory and software development fundamentals to produce computing-based solutions.\"\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    // Indicators for each outcome\r\n");
      out.write("    const indicators = {\r\n");
      out.write("        1: [\r\n");
      out.write("            \"1.1 Student can correctly interpret a computational problem and define its parameters\",\r\n");
      out.write("            \"1.2 Student can analyze a computational problem in order to choose mathematical and algorithmic principles that can be applied to solve the problem\",\r\n");
      out.write("            \"1.3 Student can define a solution to a computational problem\",\r\n");
      out.write("            \"1.4 Student can effectively collect and document system requirements\",\r\n");
      out.write("            \"1.5 Student can effectively analyze and model a problem domain\",\r\n");
      out.write("            \"1.6 Student can identify the relative efficiency of different algorithms using asymptotic notation\"\r\n");
      out.write("        ],\r\n");
      out.write("        2: [\r\n");
      out.write("            \"2.1 Student can identify and evaluate appropriate technologies to be used in a system\",\r\n");
      out.write("            \"2.2 Student can effectively construct a design model of a system\",\r\n");
      out.write("            \"2.3 Student can effectively incorporate requirements outside the problem domain (e.g., a user interface) into the design model\",\r\n");
      out.write("            \"2.4 Student can plan and implement a testing strategy to ensure that system meets its quality goal\",\r\n");
      out.write("            \"2.5 Student can collect and analyze runtime benchmark data to characterize the efficiency of an algorithm or data structure\",\r\n");
      out.write("            \"2.6 Student can specify appropriate security concerns and requirements for a component or system\",\r\n");
      out.write("            \"2.7 Student can evaluate a component or system to identify security characteristics and identify vulnerabilities\"\r\n");
      out.write("        ],\r\n");
      out.write("        3: [\r\n");
      out.write("            \"3.1 Student can write a clear and well-organized technical report\",\r\n");
      out.write("            \"3.2 Student can create and present a clear and well-organized technical presentation using appropriate visual, textual, and spoken content\",\r\n");
      out.write("            \"3.3 Student can communicate technical content to peers\",\r\n");
      out.write("            \"3.4 Student can communicate technical content to general audiences\"\r\n");
      out.write("        ],\r\n");
      out.write("        4: [\r\n");
      out.write("            \"4.1 Student can analyze and explain the ethical issues surrounding a particular computing topic (for example, peer-to-peer file sharing)\",\r\n");
      out.write("            \"4.2 Student demonstrates recognition of his or her professional responsibilities as a member of the computing profession\"\r\n");
      out.write("        ],\r\n");
      out.write("        5: [\r\n");
      out.write("            \"5.1 Student demonstrates an ability to participate in and implement processes for team communication and coordination\",\r\n");
      out.write("            \"5.2 Student demonstrates an ability to work closely with other students to solve technical problems\"\r\n");
      out.write("        ],\r\n");
      out.write("        6: [\r\n");
      out.write("            \"6.1 Student is proficient in a current programming language\",\r\n");
      out.write("            \"6.2 Student can create user interfaces using current platforms\",\r\n");
      out.write("            \"6.3 Student can write programs that use concurrency\",\r\n");
      out.write("            \"6.4 Student can implement automated tests to satisfy the goals of a testing strategy\",\r\n");
      out.write("            \"6.5 Student can use appropriate implementation techniques and practices to meet security requirements and/or mitigate discovered vulnerabilities\"\r\n");
      out.write("        ]\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    // Course to outcomes mapping\r\n");
      out.write("    const courseOutcomes = {\r\n");
      out.write("        \"CS101\": [1, 6],\r\n");
      out.write("        \"CS201\": [1, 2, 6],\r\n");
      out.write("        \"CS320\": [1, 2, 3, 5, 6],\r\n");
      out.write("        \"CS330\": [2, 4],\r\n");
      out.write("        \"CS335\": [2, 4, 6],\r\n");
      out.write("        \"CS340\": [6],\r\n");
      out.write("        \"CS350\": [1],\r\n");
      out.write("        \"CS360\": [1, 2],\r\n");
      out.write("        \"CS420\": [6],\r\n");
      out.write("        \"CS456\": [4],\r\n");
      out.write("        \"CS481\": [1, 2, 3, 5, 6],\r\n");
      out.write("        \"CS400\": [1, 2, 3, 5, 6]\r\n");
      out.write("    };\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    // Function to show the outcomes for the selected course\r\n");
      out.write("    function updateOutcomes() {\r\n");
      out.write("        const dynamicOutcomesDiv = document.getElementById('dynamicCourseOutcomes');\r\n");
      out.write("        const placeholderDiv = document.getElementById('courseOutcomesPlaceholder');\r\n");
      out.write("\r\n");
      out.write("        // Get the selected course\r\n");
      out.write("        const selectedCourse = document.getElementById('courseId').value;\r\n");
      out.write("\r\n");
      out.write("        // If no course is selected, show placeholder and hide outcomes\r\n");
      out.write("        if (!selectedCourse || !courseOutcomes[selectedCourse]) {\r\n");
      out.write("            placeholderDiv.style.display = 'block';\r\n");
      out.write("            dynamicOutcomesDiv.style.display = 'none';\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Hide placeholder and show dynamic outcomes\r\n");
      out.write("        placeholderDiv.style.display = 'none';\r\n");
      out.write("        dynamicOutcomesDiv.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("        // Clear previous content\r\n");
      out.write("        dynamicOutcomesDiv.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("        // Add header\r\n");
      out.write("        const header = document.createElement('h3');\r\n");
      out.write("        header.textContent = `Outcomes for ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("        dynamicOutcomesDiv.appendChild(header);\r\n");
      out.write("\r\n");
      out.write("        // Add description\r\n");
      out.write("        const description = document.createElement('p');\r\n");
      out.write("        description.textContent = 'The following outcomes are automatically assigned based on the course. You can select which indicators to include for each outcome.';\r\n");
      out.write("        dynamicOutcomesDiv.appendChild(description);\r\n");
      out.write("\r\n");
      out.write("        // Generate outcome sections\r\n");
      out.write("        courseOutcomes[selectedCourse].forEach(outcomeId => {\r\n");
      out.write("            // Create outcome container\r\n");
      out.write("            const outcomeContainer = document.createElement('div');\r\n");
      out.write("            outcomeContainer.className = 'outcome-container';\r\n");
      out.write("\r\n");
      out.write("            // Create outcome checkbox container\r\n");
      out.write("            const outcomeCheckboxContainer = document.createElement('div');\r\n");
      out.write("            outcomeCheckboxContainer.style.display = 'flex';\r\n");
      out.write("            outcomeCheckboxContainer.style.alignItems = 'center';\r\n");
      out.write("            outcomeCheckboxContainer.style.marginBottom = '10px';\r\n");
      out.write("\r\n");
      out.write("            // Create outcome checkbox\r\n");
      out.write("            const outcomeCheckbox = document.createElement('input');\r\n");
      out.write("            outcomeCheckbox.type = 'checkbox';\r\n");
      out.write("            outcomeCheckbox.id = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_outcome_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            outcomeCheckbox.name = `selectedOutcome_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            outcomeCheckbox.value = outcomeId;\r\n");
      out.write("            outcomeCheckbox.checked = true;\r\n");
      out.write("            outcomeCheckbox.style.marginRight = '10px';\r\n");
      out.write("\r\n");
      out.write("            // Add event listener to toggle indicators when outcome is checked/unchecked\r\n");
      out.write("            outcomeCheckbox.addEventListener('change', function() {\r\n");
      out.write("                const indicatorsDiv = document.getElementById(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_indicators_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("                if (indicatorsDiv) {\r\n");
      out.write("                    indicatorsDiv.style.display = this.checked ? 'block' : 'none';\r\n");
      out.write("\r\n");
      out.write("                    // Enable/disable indicator checkboxes\r\n");
      out.write("                    const indicatorCheckboxes = indicatorsDiv.querySelectorAll('input[type=\"checkbox\"]');\r\n");
      out.write("                    indicatorCheckboxes.forEach(checkbox => {\r\n");
      out.write("                        checkbox.disabled = !this.checked;\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Create outcome label\r\n");
      out.write("            const outcomeLabel = document.createElement('label');\r\n");
      out.write("            outcomeLabel.htmlFor = outcomeCheckbox.id;\r\n");
      out.write("            outcomeLabel.className = 'outcome-label';\r\n");
      out.write("            outcomeLabel.textContent = `Outcome ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeDescriptions[outcomeId]}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("\r\n");
      out.write("            // Add checkbox and label to container\r\n");
      out.write("            outcomeCheckboxContainer.appendChild(outcomeCheckbox);\r\n");
      out.write("            outcomeCheckboxContainer.appendChild(outcomeLabel);\r\n");
      out.write("\r\n");
      out.write("            // Add outcome checkbox container to outcome container\r\n");
      out.write("            outcomeContainer.appendChild(outcomeCheckboxContainer);\r\n");
      out.write("\r\n");
      out.write("            // Add indicators label\r\n");
      out.write("            const indicatorsLabel = document.createElement('div');\r\n");
      out.write("            indicatorsLabel.className = 'indicators-label';\r\n");
      out.write("            indicatorsLabel.textContent = 'Select Indicators:';\r\n");
      out.write("            outcomeContainer.appendChild(indicatorsLabel);\r\n");
      out.write("\r\n");
      out.write("            // Create indicators container with ID for toggling\r\n");
      out.write("            const indicatorsDiv = document.createElement('div');\r\n");
      out.write("            indicatorsDiv.id = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_indicators_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            indicatorsDiv.style.display = 'block'; // Initially visible since outcome is checked by default\r\n");
      out.write("\r\n");
      out.write("            // Add indicators\r\n");
      out.write("            if (indicators[outcomeId]) {\r\n");
      out.write("                indicators[outcomeId].forEach((indicator, index) => {\r\n");
      out.write("                    // Extract indicator number (e.g., \"1.1\" from \"1.1 Student can...\")\r\n");
      out.write("                    const indicatorNumber = indicator.split(' ')[0];\r\n");
      out.write("\r\n");
      out.write("                    // Create indicator container\r\n");
      out.write("                    const indicatorContainer = document.createElement('div');\r\n");
      out.write("                    indicatorContainer.className = 'indicator-container';\r\n");
      out.write("\r\n");
      out.write("                    // Create checkbox\r\n");
      out.write("                    const checkbox = document.createElement('input');\r\n");
      out.write("                    checkbox.type = 'checkbox';\r\n");
      out.write("                    checkbox.id = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_indicator_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${indicatorNumber.replace('.', '_')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("                    checkbox.name = `indicator_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${indicatorNumber.replace('.', '_')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("                    checkbox.value = indicatorNumber;\r\n");
      out.write("                    checkbox.checked = true;\r\n");
      out.write("\r\n");
      out.write("                    // Create label\r\n");
      out.write("                    const label = document.createElement('label');\r\n");
      out.write("                    label.htmlFor = checkbox.id;\r\n");
      out.write("                    label.textContent = indicator;\r\n");
      out.write("\r\n");
      out.write("                    // Add checkbox and label to container\r\n");
      out.write("                    indicatorContainer.appendChild(checkbox);\r\n");
      out.write("                    indicatorContainer.appendChild(document.createTextNode(' '));\r\n");
      out.write("                    indicatorContainer.appendChild(label);\r\n");
      out.write("\r\n");
      out.write("                    // Add indicator to indicators container\r\n");
      out.write("                    indicatorsDiv.appendChild(indicatorContainer);\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Add indicators container to outcome container\r\n");
      out.write("            outcomeContainer.appendChild(indicatorsDiv);\r\n");
      out.write("\r\n");
      out.write("            // Add outcome container to dynamic outcomes div\r\n");
      out.write("            dynamicOutcomesDiv.appendChild(outcomeContainer);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to collect selected outcomes and update the hidden input\r\n");
      out.write("    function updateSelectedOutcomesInput() {\r\n");
      out.write("        const selectedCourse = document.getElementById('courseId').value;\r\n");
      out.write("        if (!selectedCourse || !courseOutcomes[selectedCourse]) {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const selectedOutcomes = [];\r\n");
      out.write("        courseOutcomes[selectedCourse].forEach(outcomeId => {\r\n");
      out.write("            const checkbox = document.getElementById(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_outcome_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("            if (checkbox && checkbox.checked) {\r\n");
      out.write("                selectedOutcomes.push(outcomeId);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('selectedOutcomesInput').value = selectedOutcomes.join(',');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Add event listeners\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        // Course select dropdown\r\n");
      out.write("        const courseSelect = document.getElementById('courseId');\r\n");
      out.write("        if (courseSelect) {\r\n");
      out.write("            courseSelect.addEventListener('change', updateOutcomes);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Form submission\r\n");
      out.write("        const form = document.getElementById('createFcarForm');\r\n");
      out.write("        if (form) {\r\n");
      out.write("            form.addEventListener('submit', function(event) {\r\n");
      out.write("                // Update the selected outcomes input before submitting\r\n");
      out.write("                updateSelectedOutcomesInput();\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
