/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.9
 * Generated at: 2025-04-28 06:51:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;
import com.ABETAppTeam.model.FCAR;
import com.ABETAppTeam.model.Course;
import com.ABETAppTeam.model.User;
import com.ABETAppTeam.model.Professor;
import com.ABETAppTeam.model.Department;
import java.util.HashMap;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.ABETAppTeam.model.Professor");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ABETAppTeam.model.User");
    _jspx_imports_classes.add("com.ABETAppTeam.model.Department");
    _jspx_imports_classes.add("com.ABETAppTeam.model.Course");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.ABETAppTeam.model.FCAR");
    _jspx_imports_classes.add("java.util.HashMap");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Admin Dashboard</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/navbar.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"dashboard\" id=\"adminDashboard\">\r\n");
      out.write("    <div class=\"header-container\">\r\n");
      out.write("        <h1>Admin Dashboard</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Status Key -->\r\n");
      out.write("    <div class=\"status-key\">\r\n");
      out.write("        <div><span class=\"status draft\"></span> Draft</div>\r\n");
      out.write("        <div><span class=\"status submitted\"></span> Submitted</div>\r\n");
      out.write("        <div><span class=\"status approved\"></span> Approved</div>\r\n");
      out.write("        <div><span class=\"status rejected\"></span> Rejected</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Statistics Section -->\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Dashboard Statistics</h2>\r\n");
      out.write("        <div class=\"stat-container\">\r\n");
      out.write("            ");

                List<FCAR> allFCARs = (List<FCAR>) request.getAttribute("allFCARs");
                Map<String, Integer> fcarStatusCounts = (Map<String, Integer>) request.getAttribute("fcarStatusCounts");
                if (fcarStatusCounts == null) {
                    fcarStatusCounts = new HashMap<>();
                }

                int totalFCARs = allFCARs != null ? allFCARs.size() : 0;
                int draftCount = fcarStatusCounts.getOrDefault("Draft", 0);
                int submittedCount = fcarStatusCounts.getOrDefault("Submitted", 0);
                int approvedCount = fcarStatusCounts.getOrDefault("Approved", 0);
                int rejectedCount = fcarStatusCounts.getOrDefault("Rejected", 0);
            
      out.write("\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Total FCARs</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( totalFCARs );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Draft</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( draftCount );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Submitted</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( submittedCount );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Approved</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( approvedCount );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"stat-box\">\r\n");
      out.write("                <h3>Rejected</h3>\r\n");
      out.write("                <div class=\"stat-number\">");
      out.print( rejectedCount );
      out.write("</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Action Buttons -->\r\n");
      out.write("    <div class=\"action-buttons\">\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ViewFCARServlet\" method=\"get\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"viewAll\"/>\r\n");
      out.write("            <button type=\"submit\" class=\"btn\">View All FCARs</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- View FCARs Section -->\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Manage FCARs</h2>\r\n");
      out.write("\r\n");
      out.write("        <!-- Dynamically display all FCARs -->\r\n");
      out.write("        <div id=\"fcarList\">\r\n");
      out.write("            <h3>Existing FCARs</h3>\r\n");
      out.write("            ");

                if (allFCARs != null && !allFCARs.isEmpty()) {
            
      out.write("\r\n");
      out.write("            <div class=\"fcar-box\">\r\n");
      out.write("                ");

                    for (FCAR fcar : allFCARs) {
                        String status = fcar.getStatus().toLowerCase();
                
      out.write("\r\n");
      out.write("                <div class=\"fcar-item\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <span class=\"status ");
      out.print( status );
      out.write("\"></span>\r\n");
      out.write("                        <strong>Course:</strong> ");
      out.print( fcar.getCourseId() );
      out.write(" -\r\n");
      out.write("                        <strong>Professor:</strong> ");
      out.print( fcar.getProfessorId() );
      out.write(" -\r\n");
      out.write("                        <strong>Semester:</strong> ");
      out.print( fcar.getSemester() );
      out.write(' ');
      out.print( fcar.getYear() );
      out.write(" -\r\n");
      out.write("                        <strong>Status:</strong> ");
      out.print( fcar.getStatus() );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fcar-actions\">\r\n");
      out.write("                        <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ViewFCARServlet\" style=\"display:inline;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"fcarId\" value=\"");
      out.print( fcar.getFcarId() );
      out.write("\"/>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\">View</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" style=\"display:inline;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"editFCAR\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"fcarId\" value=\"");
      out.print( fcar.getFcarId() );
      out.write("\"/>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\">Edit</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        ");
 if ("submitted".equals(status)) { 
      out.write("\r\n");
      out.write("                        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" style=\"display:inline;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"approveFCAR\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"fcarId\" value=\"");
      out.print( fcar.getFcarId() );
      out.write("\"/>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\" style=\"background-color: var(--success);\">Approve</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" style=\"display:inline;\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"action\" value=\"rejectFCAR\"/>\r\n");
      out.write("                            <input type=\"hidden\" name=\"fcarId\" value=\"");
      out.print( fcar.getFcarId() );
      out.write("\"/>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn\" style=\"background-color: var(--danger);\">Reject</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <p>No FCARs available.</p>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 'Create New FCAR' section -->\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Create New FCAR</h2>\r\n");
      out.write("        <div class=\"form-section\">\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" method=\"post\" id=\"createFcarForm\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"createFCAR\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"selectedOutcomes\" id=\"selectedOutcomesInput\" value=\"\" />\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"courseId\">Course:</label>\r\n");
      out.write("                    <select id=\"courseId\" name=\"courseId\" required>\r\n");
      out.write("                        <option value=\"\">Select a Course</option>\r\n");
      out.write("                        ");

                            List<Course> courses = (List<Course>) request.getAttribute("courses");
                            if (courses != null && !courses.isEmpty()) {
                                for (Course course : courses) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( course.getCourseCode() );
      out.write('"');
      out.write('>');
      out.print( course.getCourseCode() );
      out.write(':');
      out.write(' ');
      out.print( course.getCourseName() );
      out.write("</option>\r\n");
      out.write("                        ");

                                }
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"professorId\">Assign to Professor:</label>\r\n");
      out.write("                    <select id=\"professorId\" name=\"professorId\" required>\r\n");
      out.write("                        <option value=\"\">Select a Professor</option>\r\n");
      out.write("                        ");

                            List<User> professors = (List<User>) request.getAttribute("professors");
                            if (professors != null && !professors.isEmpty()) {
                                for (User professor : professors) {
                                    if (professor instanceof Professor) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( professor.getUserId() );
      out.write('"');
      out.write('>');
      out.print( professor.getFirstName() );
      out.write(' ');
      out.print( professor.getLastName() );
      out.write("</option>\r\n");
      out.write("                        ");

                                    }
                                }
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"semester\">Semester:</label>\r\n");
      out.write("                    <select id=\"semester\" name=\"semester\" required>\r\n");
      out.write("                        <option value=\"Spring\">Spring</option>\r\n");
      out.write("                        <option value=\"Summer\">Summer</option>\r\n");
      out.write("                        <option value=\"Fall\">Fall</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"year\">Year:</label>\r\n");
      out.write("                    <input type=\"number\" id=\"year\" name=\"year\" min=\"2020\" max=\"2030\" value=\"2025\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Outcomes and Indicators Section -->\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Student Learning Outcomes and Indicators:</label>\r\n");
      out.write("                    <div id=\"outcomesContainer\" class=\"outcomes-container\">\r\n");
      out.write("                        <div id=\"courseOutcomesPlaceholder\">\r\n");
      out.write("                            <p>Please select a course to see the associated outcomes and indicators.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Dynamic Course Outcomes Container -->\r\n");
      out.write("                        <div id=\"dynamicCourseOutcomes\" style=\"display: none;\">\r\n");
      out.write("                            <!-- This will be populated dynamically by JavaScript -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"targetGoal\">Target Goal (%):</label>\r\n");
      out.write("                    <input type=\"number\" id=\"targetGoal\" name=\"targetGoal\" min=\"0\" max=\"100\" value=\"70\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn-submit\">Create FCAR</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 'Manage Users' section moved to the bottom -->\r\n");
      out.write("    <div class=\"section\">\r\n");
      out.write("        <h2>Manage Users</h2>\r\n");
      out.write("        <div class=\"form-section\">\r\n");
      out.write("            <h3>Create New Professor Account</h3>\r\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" method=\"post\" id=\"createUserForm\">\r\n");
      out.write("                <input type=\"hidden\" name=\"action\" value=\"createUser\" />\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"firstName\">First Name:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"firstName\" name=\"firstName\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"lastName\">Last Name:</label>\r\n");
      out.write("                    <input type=\"text\" id=\"lastName\" name=\"lastName\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"email\">Email:</label>\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"password\">Password:</label>\r\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"department\">Department:</label>\r\n");
      out.write("                    <select id=\"department\" name=\"deptId\" required>\r\n");
      out.write("                        <option value=\"\">Select a Department</option>\r\n");
      out.write("                        ");

                            List<Department> departments = (List<Department>) request.getAttribute("departments");
                            if (departments != null && !departments.isEmpty()) {
                                for (Department dept : departments) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print( dept.getId() );
      out.write('"');
      out.write('>');
      out.print( dept.getName() );
      out.write("</option>\r\n");
      out.write("                        ");

                                }
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label>Assign Courses:</label>\r\n");
      out.write("                    <div class=\"course-checkboxes\">\r\n");
      out.write("                        ");

                            if (courses != null && !courses.isEmpty()) {
                                for (Course course : courses) {
                        
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <input type=\"checkbox\" id=\"course_");
      out.print( course.getCourseCode() );
      out.write("\" name=\"assignedCourses\" value=\"");
      out.print( course.getCourseCode() );
      out.write("\" />\r\n");
      out.write("                            <label for=\"course_");
      out.print( course.getCourseCode() );
      out.write('"');
      out.write('>');
      out.print( course.getCourseCode() );
      out.write(':');
      out.write(' ');
      out.print( course.getCourseName() );
      out.write("</label>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        ");

                                }
                            }
                        
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn-submit\">Create Professor Account</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Existing Professors List -->\r\n");
      out.write("        <div class=\"form-section\">\r\n");
      out.write("            <h3>Existing Professors</h3>\r\n");
      out.write("            <div class=\"user-list\">\r\n");
      out.write("                ");

                    if (professors != null && !professors.isEmpty()) {
                
      out.write("\r\n");
      out.write("                <table class=\"data-table\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>ID</th>\r\n");
      out.write("                        <th>Name</th>\r\n");
      out.write("                        <th>Email</th>\r\n");
      out.write("                        <th>Department</th>\r\n");
      out.write("                        <th>Status</th>\r\n");
      out.write("                        <th>Actions</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    ");

                        for (User user : professors) {
                            if (user instanceof Professor) {
                                Professor professor = (Professor) user;
                    
      out.write("\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print( professor.getUserId() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( professor.getFirstName() );
      out.write(' ');
      out.print( professor.getLastName() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( professor.getEmail() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( professor.getDeptName() );
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print( professor.isActive() ? "Active" : "Inactive" );
      out.write("</td>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            <button type=\"button\" class=\"btn\" onclick=\"openEditUserModal(");
      out.print( professor.getUserId() );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( professor.getFirstName() );
      out.write("', '");
      out.print( professor.getLastName() );
      out.write("', '");
      out.print( professor.getEmail() );
      out.write('\'');
      out.write(',');
      out.write(' ');
      out.print( professor.getDeptId() );
      out.write(")\">Edit</button>\r\n");
      out.write("                            <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" class=\"inline\">\r\n");
      out.write("                                <input type=\"hidden\" name=\"action\" value=\"toggleUserStatus\" />\r\n");
      out.write("                                <input type=\"hidden\" name=\"userId\" value=\"");
      out.print( professor.getUserId() );
      out.write("\" />\r\n");
      out.write("                                <button type=\"submit\" class=\"btn ");
      out.print( professor.isActive() ? "btn-danger" : "btn-success" );
      out.write("\">\r\n");
      out.write("                                    ");
      out.print( professor.isActive() ? "Deactivate" : "Activate" );
      out.write("\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                <p>No professors found.</p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Edit User Modal -->\r\n");
      out.write("<div id=\"editUserModal\" class=\"modal\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeEditUserModal()\">&times;</span>\r\n");
      out.write("        <h2>Edit Professor</h2>\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet\" method=\"post\" id=\"editUserForm\">\r\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"editUser\" />\r\n");
      out.write("            <input type=\"hidden\" name=\"userId\" id=\"editUserId\" />\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"editFirstName\">First Name:</label>\r\n");
      out.write("                <input type=\"text\" id=\"editFirstName\" name=\"firstName\" required />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"editLastName\">Last Name:</label>\r\n");
      out.write("                <input type=\"text\" id=\"editLastName\" name=\"lastName\" required />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"editEmail\">Email:</label>\r\n");
      out.write("                <input type=\"email\" id=\"editEmail\" name=\"email\" required />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"editPassword\">New Password (leave blank to keep current):</label>\r\n");
      out.write("                <input type=\"password\" id=\"editPassword\" name=\"password\" />\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"editDepartment\">Department:</label>\r\n");
      out.write("                <select id=\"editDepartment\" name=\"deptId\" required>\r\n");
      out.write("                    <option value=\"\">Select a Department</option>\r\n");
      out.write("                    ");

                        if (departments != null && !departments.isEmpty()) {
                            for (Department dept : departments) {
                    
      out.write("\r\n");
      out.write("                    <option value=\"");
      out.print( dept.getId() );
      out.write('"');
      out.write('>');
      out.print( dept.getName() );
      out.write("</option>\r\n");
      out.write("                    ");

                            }
                        }
                    
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label>Assign Courses:</label>\r\n");
      out.write("                <div class=\"course-checkboxes\" id=\"editCourseCheckboxes\">\r\n");
      out.write("                    <!-- Will be populated dynamically -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"button-container\">\r\n");
      out.write("                <button type=\"button\" class=\"btn-cancel\" onclick=\"closeEditUserModal()\">Cancel</button>\r\n");
      out.write("                <button type=\"submit\" class=\"btn-submit\">Save Changes</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Get outcomeData from the controller\r\n");
      out.write("    ");
 
    String outcomeData = (String) request.getAttribute("outcomeData");
    if (outcomeData != null && !outcomeData.isEmpty()) {
        out.println(outcomeData);
    } 
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    // Function to show the outcomes for the selected course\r\n");
      out.write("    function updateOutcomes() {\r\n");
      out.write("        const dynamicOutcomesDiv = document.getElementById('dynamicCourseOutcomes');\r\n");
      out.write("        const placeholderDiv = document.getElementById('courseOutcomesPlaceholder');\r\n");
      out.write("\r\n");
      out.write("        // Get the selected course\r\n");
      out.write("        const selectedCourse = document.getElementById('courseId').value;\r\n");
      out.write("\r\n");
      out.write("        // If no course is selected, show placeholder and hide outcomes\r\n");
      out.write("        if (!selectedCourse || !courseOutcomes[selectedCourse]) {\r\n");
      out.write("            placeholderDiv.style.display = 'block';\r\n");
      out.write("            dynamicOutcomesDiv.style.display = 'none';\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Hide placeholder and show dynamic outcomes\r\n");
      out.write("        placeholderDiv.style.display = 'none';\r\n");
      out.write("        dynamicOutcomesDiv.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("        // Clear previous content\r\n");
      out.write("        dynamicOutcomesDiv.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("        // Add header\r\n");
      out.write("        const header = document.createElement('h3');\r\n");
      out.write("        header.textContent = `Outcomes for ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("        dynamicOutcomesDiv.appendChild(header);\r\n");
      out.write("\r\n");
      out.write("        // Add description\r\n");
      out.write("        const description = document.createElement('p');\r\n");
      out.write("        description.textContent = 'The following outcomes are automatically assigned based on the course. You can select which indicators to include for each outcome.';\r\n");
      out.write("        dynamicOutcomesDiv.appendChild(description);\r\n");
      out.write("\r\n");
      out.write("        // Generate outcome sections\r\n");
      out.write("        courseOutcomes[selectedCourse].forEach(outcomeId => {\r\n");
      out.write("            // Create outcome container\r\n");
      out.write("            const outcomeContainer = document.createElement('div');\r\n");
      out.write("            outcomeContainer.className = 'outcome-container';\r\n");
      out.write("\r\n");
      out.write("            // Create an outcome checkbox container\r\n");
      out.write("            const outcomeCheckboxContainer = document.createElement('div');\r\n");
      out.write("            outcomeCheckboxContainer.className = 'outcome-checkbox-container';\r\n");
      out.write("\r\n");
      out.write("            // Create an outcome checkbox\r\n");
      out.write("            const outcomeCheckbox = document.createElement('input');\r\n");
      out.write("            outcomeCheckbox.type = 'checkbox';\r\n");
      out.write("            outcomeCheckbox.id = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_outcome_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            outcomeCheckbox.name = `selectedOutcome_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            outcomeCheckbox.value = outcomeId;\r\n");
      out.write("            outcomeCheckbox.checked = true;\r\n");
      out.write("            outcomeCheckbox.className = 'outcome-checkbox';\r\n");
      out.write("\r\n");
      out.write("            // Add event listener to toggle indicators when outcome is checked/unchecked\r\n");
      out.write("            outcomeCheckbox.addEventListener('change', function() {\r\n");
      out.write("                const indicatorsDiv = document.getElementById(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_indicators_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("                if (indicatorsDiv) {\r\n");
      out.write("                    indicatorsDiv.style.display = this.checked ? 'block' : 'none';\r\n");
      out.write("\r\n");
      out.write("                    // Enable/disable indicator checkboxes\r\n");
      out.write("                    const indicatorCheckboxes = indicatorsDiv.querySelectorAll('input[type=\"checkbox\"]');\r\n");
      out.write("                    indicatorCheckboxes.forEach(checkbox => {\r\n");
      out.write("                        checkbox.disabled = !this.checked;\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            // Create outcome label\r\n");
      out.write("            const outcomeLabel = document.createElement('label');\r\n");
      out.write("            outcomeLabel.htmlFor = outcomeCheckbox.id;\r\n");
      out.write("            outcomeLabel.className = 'outcome-label';\r\n");
      out.write("            outcomeLabel.textContent = `Outcome ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(':');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeDescriptions[outcomeId]}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("\r\n");
      out.write("            // Add checkbox and label to container\r\n");
      out.write("            outcomeCheckboxContainer.appendChild(outcomeCheckbox);\r\n");
      out.write("            outcomeCheckboxContainer.appendChild(outcomeLabel);\r\n");
      out.write("\r\n");
      out.write("            // Add outcome checkbox container to outcome container\r\n");
      out.write("            outcomeContainer.appendChild(outcomeCheckboxContainer);\r\n");
      out.write("\r\n");
      out.write("            // Add indicators label\r\n");
      out.write("            const indicatorsLabel = document.createElement('div');\r\n");
      out.write("            indicatorsLabel.className = 'indicators-label';\r\n");
      out.write("            indicatorsLabel.textContent = 'Select Indicators:';\r\n");
      out.write("            outcomeContainer.appendChild(indicatorsLabel);\r\n");
      out.write("\r\n");
      out.write("            // Create indicators container with ID for toggling\r\n");
      out.write("            const indicatorsDiv = document.createElement('div');\r\n");
      out.write("            indicatorsDiv.id = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_indicators_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            indicatorsDiv.style.display = 'block'; // Initially visible since outcome is checked by default\r\n");
      out.write("\r\n");
      out.write("            // Add indicators\r\n");
      out.write("            if (indicators[outcomeId]) {\r\n");
      out.write("                indicators[outcomeId].forEach((indicator, index) => {\r\n");
      out.write("                    // Extract indicator number (e.g., \"1.1\" from \"1.1 Student can...\")\r\n");
      out.write("                    const indicatorNumber = indicator.split(' ')[0];\r\n");
      out.write("\r\n");
      out.write("                    // Create indicator container\r\n");
      out.write("                    const indicatorContainer = document.createElement('div');\r\n");
      out.write("                    indicatorContainer.className = 'indicator-container';\r\n");
      out.write("\r\n");
      out.write("                    // Create checkbox\r\n");
      out.write("                    const checkbox = document.createElement('input');\r\n");
      out.write("                    checkbox.type = 'checkbox';\r\n");
      out.write("                    checkbox.id = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_indicator_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${indicatorNumber.replace('.', '_')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("                    checkbox.name = `indicator_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${indicatorNumber.replace('.', '_')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("                    checkbox.value = indicatorNumber;\r\n");
      out.write("                    checkbox.checked = true;\r\n");
      out.write("\r\n");
      out.write("                    // Create label\r\n");
      out.write("                    const label = document.createElement('label');\r\n");
      out.write("                    label.htmlFor = checkbox.id;\r\n");
      out.write("                    label.textContent = indicator;\r\n");
      out.write("\r\n");
      out.write("                    // Add checkbox and label to container\r\n");
      out.write("                    indicatorContainer.appendChild(checkbox);\r\n");
      out.write("                    indicatorContainer.appendChild(document.createTextNode(' '));\r\n");
      out.write("                    indicatorContainer.appendChild(label);\r\n");
      out.write("\r\n");
      out.write("                    // Add indicator to indicators container\r\n");
      out.write("                    indicatorsDiv.appendChild(indicatorContainer);\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Add indicators container to outcome container\r\n");
      out.write("            outcomeContainer.appendChild(indicatorsDiv);\r\n");
      out.write("\r\n");
      out.write("            // Add outcome container to dynamic outcomes div\r\n");
      out.write("\r\n");
      out.write("            // Add outcome container to dynamic outcomes div\r\n");
      out.write("            dynamicOutcomesDiv.appendChild(outcomeContainer);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to collect selected outcomes and update the hidden input\r\n");
      out.write("    function updateSelectedOutcomesInput() {\r\n");
      out.write("        const selectedCourse = document.getElementById('courseId').value;\r\n");
      out.write("        if (!selectedCourse || !courseOutcomes[selectedCourse]) {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        const selectedOutcomes = [];\r\n");
      out.write("        courseOutcomes[selectedCourse].forEach(outcomeId => {\r\n");
      out.write("            const checkbox = document.getElementById(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${selectedCourse}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("_outcome_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outcomeId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`);\r\n");
      out.write("            if (checkbox && checkbox.checked) {\r\n");
      out.write("                selectedOutcomes.push(outcomeId);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('selectedOutcomesInput').value = selectedOutcomes.join(',');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to open the edit user modal\r\n");
      out.write("    function openEditUserModal(userId, firstName, lastName, email, deptId) {\r\n");
      out.write("        // Set form values\r\n");
      out.write("        document.getElementById('editUserId').value = userId;\r\n");
      out.write("        document.getElementById('editFirstName').value = firstName;\r\n");
      out.write("        document.getElementById('editLastName').value = lastName;\r\n");
      out.write("        document.getElementById('editEmail').value = email;\r\n");
      out.write("        document.getElementById('editDepartment').value = deptId;\r\n");
      out.write("\r\n");
      out.write("        // Populate course checkboxes\r\n");
      out.write("        populateEditCourseCheckboxes(userId);\r\n");
      out.write("\r\n");
      out.write("        // Show the modal\r\n");
      out.write("        document.getElementById('editUserModal').style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to close the edit user modal\r\n");
      out.write("    function closeEditUserModal() {\r\n");
      out.write("        document.getElementById('editUserModal').style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to populate course checkboxes in the edit modal\r\n");
      out.write("    function populateEditCourseCheckboxes(userId) {\r\n");
      out.write("        const container = document.getElementById('editCourseCheckboxes');\r\n");
      out.write("        container.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("        // Make an AJAX call to get assigned courses for this professor\r\n");
      out.write("        fetch(`");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AdminServlet?action=getProfessorCourses&userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`)\r\n");
      out.write("            .then(response => response.json())\r\n");
      out.write("            .then(assignedCourses => {\r\n");
      out.write("                // Get all available courses from the courses array\r\n");
      out.write("                const courseSelect = document.getElementById('courseId');\r\n");
      out.write("                const options = Array.from(courseSelect.options);\r\n");
      out.write("\r\n");
      out.write("                // Skip the first option which is \"Select a Course\"\r\n");
      out.write("                for (let i = 1; i < options.length; i++) {\r\n");
      out.write("                    const courseCode = options[i].value;\r\n");
      out.write("                    const courseName = options[i].text;\r\n");
      out.write("\r\n");
      out.write("                    const courseDiv = document.createElement('div');\r\n");
      out.write("                    const checkbox = document.createElement('input');\r\n");
      out.write("                    checkbox.type = 'checkbox';\r\n");
      out.write("                    checkbox.id = `edit_course_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseCode}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("                    checkbox.name = 'assignedCourses';\r\n");
      out.write("                    checkbox.value = courseCode;\r\n");
      out.write("                    checkbox.checked = assignedCourses.includes(courseCode);\r\n");
      out.write("\r\n");
      out.write("                    const label = document.createElement('label');\r\n");
      out.write("                    label.htmlFor = `edit_course_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseCode}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("                    label.textContent = courseName;\r\n");
      out.write("\r\n");
      out.write("                    courseDiv.appendChild(checkbox);\r\n");
      out.write("                    courseDiv.appendChild(document.createTextNode(' '));\r\n");
      out.write("                    courseDiv.appendChild(label);\r\n");
      out.write("\r\n");
      out.write("                    container.appendChild(courseDiv);\r\n");
      out.write("                }\r\n");
      out.write("            })\r\n");
      out.write("            .catch(error => {\r\n");
      out.write("                console.error('Error fetching assigned courses:', error);\r\n");
      out.write("                // Fallback: just show all courses unchecked\r\n");
      out.write("                addCoursesToModal(container, []);\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Helper function to add courses to the modal\r\n");
      out.write("    function addCoursesToModal(container, assignedCourses) {\r\n");
      out.write("        const courseSelect = document.getElementById('courseId');\r\n");
      out.write("        const options = Array.from(courseSelect.options);\r\n");
      out.write("\r\n");
      out.write("        // Skip the first option which is \"Select a Course\"\r\n");
      out.write("        for (let i = 1; i < options.length; i++) {\r\n");
      out.write("            const courseCode = options[i].value;\r\n");
      out.write("            const courseName = options[i].text;\r\n");
      out.write("\r\n");
      out.write("            const courseDiv = document.createElement('div');\r\n");
      out.write("            const checkbox = document.createElement('input');\r\n");
      out.write("            checkbox.type = 'checkbox';\r\n");
      out.write("            checkbox.id = `edit_course_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseCode}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            checkbox.name = 'assignedCourses';\r\n");
      out.write("            checkbox.value = courseCode;\r\n");
      out.write("            checkbox.checked = assignedCourses.includes(courseCode);\r\n");
      out.write("\r\n");
      out.write("            const label = document.createElement('label');\r\n");
      out.write("            label.htmlFor = `edit_course_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${courseCode}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("            label.textContent = courseName;\r\n");
      out.write("\r\n");
      out.write("            courseDiv.appendChild(checkbox);\r\n");
      out.write("            courseDiv.appendChild(document.createTextNode(' '));\r\n");
      out.write("            courseDiv.appendChild(label);\r\n");
      out.write("\r\n");
      out.write("            container.appendChild(courseDiv);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Add event listeners\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        // Course select dropdown\r\n");
      out.write("        const courseSelect = document.getElementById('courseId');\r\n");
      out.write("        if (courseSelect) {\r\n");
      out.write("            courseSelect.addEventListener('change', updateOutcomes);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Form submission\r\n");
      out.write("        const form = document.getElementById('createFcarForm');\r\n");
      out.write("        if (form) {\r\n");
      out.write("            form.addEventListener('submit', function(event) {\r\n");
      out.write("                // Update the selected outcomes input before submitting\r\n");
      out.write("                updateSelectedOutcomesInput();\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Close modal when clicking outside of it\r\n");
      out.write("        window.onclick = function(event) {\r\n");
      out.write("            const modal = document.getElementById('editUserModal');\r\n");
      out.write("            if (event.target === modal) {\r\n");
      out.write("                closeEditUserModal();\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("    });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
