name: Debug Staging Deployment

on:
  workflow_dispatch:

jobs:
  debug-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Test Environment Setup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          timeout: 60s
          command_timeout: 120s
          debug: true
          script: |
            set -ex
            echo "=== Environment Check ==="
            echo "Current directory: $(pwd)"
            echo "User: $(whoami)"
            echo "Available space: $(df -h /)"
            
            echo "=== Docker Check ==="
            docker --version || echo "Docker not installed"
            docker info | head -10 || echo "Docker not running"
            
            echo "=== Directory Check ==="
            ls -la /opt/app 2>/dev/null || echo "/opt/app does not exist"
            
            echo "=== Network Check ==="
            ping -c 3 ghcr.io || echo "Cannot reach ghcr.io"
            
            echo "=== Tailscale Check ==="
            which tailscale || echo "Tailscale not installed"
            systemctl is-active tailscaled || echo "Tailscale not running"
            
            echo "=== Firewall Check ==="
            ufw status || echo "UFW not available"

  test-docker-pull:
    runs-on: ubuntu-latest
    needs: debug-environment
    steps:
      - name: Test Docker Pull Speed
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          timeout: 300s  # 5 minutes
          command_timeout: 600s  # 10 minutes
          debug: true
          script: |
            set -ex
            echo "=== Testing Docker Pull ==="
            echo "Start time: $(date)"
            
            # Test with a small image first
            echo "Testing small image pull..."
            time docker pull alpine:latest
            
            echo "Testing GHCR connectivity..."
            echo "ghcr.io/tdavis36/abet-assessment-app:staging" | head -1
            
            echo "Attempting to pull target image..."
            timeout 300 docker pull ghcr.io/tdavis36/abet-assessment-app:staging || {
              echo "Docker pull failed or timed out"
              echo "Checking docker logs..."
              journalctl -u docker --no-pager --lines 20
              exit 1
            }
            
            echo "End time: $(date)"
            echo "=== Docker Pull Test Complete ==="

  test-network-calls:
    runs-on: ubuntu-latest
    needs: debug-environment
    steps:
      - name: Test Network Operations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          timeout: 120s
          command_timeout: 180s
          debug: true
          script: |
            set -ex
            echo "=== Testing Network Operations ==="
            
            echo "Testing Tailscale IP retrieval..."
            timeout 30 tailscale ip -4 || echo "Tailscale IP command failed"
            
            echo "Testing public IP retrieval..."
            timeout 30 curl -s ifconfig.me || echo "Public IP retrieval failed"
            
            echo "Testing alternative public IP services..."
            timeout 10 curl -s ipinfo.io/ip || echo "ipinfo.io failed"
            timeout 10 curl -s icanhazip.com || echo "icanhazip.com failed"
            
            echo "=== Network Test Complete ==="