name: Test SSH Connection

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test Basic Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          port: 22
          timeout: 30s
          command_timeout: 10s
          debug: true
          script: |
            echo "=== Connection Test ==="
            echo "Hostname: $(hostname)"
            echo "User: $(whoami)"
            echo "Directory: $(pwd)"
            echo "=== Success ==="